import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-desafio-fullstack',
  templateUrl: './desafio-fullstack.component.html',
  styleUrls: ['./desafio-fullstack.component.css']
})
export class DesafioFullstackComponent implements OnInit {

  constructor() {

   }


  dataSource = [
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },{name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
    {name: "Vinicius Pavani",
    email: "vinicius@gmail.com",
    inclusionDate: "05-03-2021",
    alterationDate: "05-03-2021",
    rule: "01",
    status: "ATIVO"  
    },
  ]
  
  columnsToDisplay = ['user', 'email', 'inclusionDate', 'alterationDate', 'rules', 'status'];
  
  ngOnInit(): void {
  }

}
